language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

services:
  - mysql

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - mysql -e 'create database mysqldump;'

script:
  - php src/Ifsnop/Mysqldump/Mysqldump.php
